### ISSUE TITLE
2FA auth failing even after following the steps in readme.

### ISSUE THREAD

**Issue by JordiLSG** [game-ci/steam-deploy#15]
Hi! 

Even after following the [steps mentioned](https://github.com/game-ci/steam-deploy/issues/4#issuecomment-751325644) in the readme section, the login keep failing : Steam Guard code:FAILED (Account Logon Denied)

I am able to login with [steamcmd ](https://github.com/CM2Walki/steamcmd) using config file and the ssfn file but not with steam-deploy.

Am I missing something? Thanks!

![image](https://user-images.githubusercontent.com/32976998/140341210-665b1e49-d0ee-4914-8d7b-e40da4648864.png)

![image](https://user-images.githubusercontent.com/32976998/140342472-4f5d7882-2b9f-435a-b834-733c127f886c.png)

**Comment by shichen85** [comment]
Having the same problem. Can log in with steamcmd but not with steam-deploy.

**Comment by davidmfinol** [comment]
PR is open that should fix this: https://github.com/game-ci/steam-deploy/pull/16

**Comment by davidmfinol** [comment]
Updated the steps in the readme with a new guide. Closing this issue, but feel free to re-open if the new steps in the README also don't work.
