### ISSUE TITLE
Unable to resolve action `game-ci/steam-deploy@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by bilalakil** [game-ci/steam-deploy#27]
**Bug description**

I see v1.0 has been tagged recently, so I expected to be able to reference the action as described in the README using `game-ci/steam-deploy@v1`, however as the title suggests this fails to be found.

**How to reproduce**

Use a workflow that has a step with:

```
      - uses: game-ci/steam-deploy@v1
```

**Expected behavior**

It should resolve to the commit tagged with v1.0.

**Comment by webbertakken** [comment]
Reopening this as the issue isn't yet resolved with #28. 

Need further investigation.

**Comment by webbertakken** [comment]
Solved.

This should now work.
