### ISSUE TITLE
How to properly generate a Base64 encoded file on Windows

### ISSUE THREAD

**Issue by pearcemichal** [game-ci/steam-deploy#39]
in the instructions, it says to use the cat command, but that command does not exist as part of the windows cmd. 

It CAN be used from powershell, but it seems it's a bit different, since using the supplied code causes it to fail, it works if you remove the "| base64" parameter, but then the file it generates is no longer base64. 

I tried writing a powershell script to encode both files and output, which seemed to do what was needed, but I am still unable to authenticate to steam, so I wonder if something is wrong with the files being generated. 

```
$config = Get-Content 'config/config.vdf'
$ssfn = Get-Content 'ssfn<your_hidden_ssfn>'

$ConfigBytes = [System.Text.Encoding]::Unicode.GetBytes($config)
$ssfnBytes = [System.Text.Encoding]::Unicode.GetBytes($ssfn)

$EncodedConfig =[Convert]::ToBase64String($ConfigBytes)
$Encodedssfn =[Convert]::ToBase64String($ssfnBytes)

$EncodedConfig | Out-File  -FilePath 'config_base64.txt' -Encoding ASCII -Width 50
$Encodedssfn | Out-File -FilePath 'ssfn_base64.txt' -Encoding ASCII -Width 50
```

If possible, could you try this, and see if the encoded files it creates for you are formatted correctly? 

Or suggest a better method, if there is one. 

Thanks!

**Comment by davidmfinol** [comment]
My recommended approach on Windows is to download Git Bash (https://git-scm.com/downloads), and use it to run `base64 $ssfnHiddenFile > ssfn_base64.txt`

**Comment by webbertakken** [comment]
As we're generally moving towards Powershell which will be more universally available I'd also recommend trying to get these kind of things to work in Powershell.

Perhaps these answers help for
- base64 encoding https://stackoverflow.com/a/53269134/3593896
- base64 decoding https://stackoverflow.com/questions/15414678/how-to-decode-a-base64-string

I'm unsure about the Width 50 part that you're using.

**Comment by pearcemichal** [comment]
tbh I'm not sure about the width thing either, but the powershell script would failed if I didn't include it. 

I already have git bash, so I tried that command and I will see if it works later. If it does, than that at least gives me an example of what the end result should look like.

**Comment by pearcemichal** [comment]
I tried using the new base64 files, but the upload still fails

here's where the issues start:

`
Loading Steam API...KeyValues Error: LoadFromBuffer: missing {   (current key: '***') in file InstallConfigStore [offset: 153]
`

since this is possible unrelated to the base64 stuff, should I make a new bug report for it?

**Comment by webbertakken** [comment]
Looks like base64 stuff just works indeed.

And yes, please create separate issues where possible. That would be great!

**Comment by pearcemichal** [comment]
will do!
