### ISSUE TITLE
Update the setup-steamcmd at the latest version

### ISSUE THREAD

**Issue by MrFastwind** [game-ci/steam-deploy#48]
**Context**

The action CyberAndrii/setup-steamcmd that you use, has been updated; the last version fixes a problem with rootless runners.

**Suggested solution**

Update the the action at the latest version

**Comment by davidmfinol** [comment]
We're planning to replace `setup-steamcmd` with a docker-based approach in https://github.com/game-ci/steam-deploy/pull/46 

@MrFastwind Could you help with the testing for that PR and see if using `steam-deploy@dcc23056f7adcaec16270b9f9715f6588c9a4c44` resolves this issue for you?

**Comment by MrFastwind** [comment]
i saw, but in the mean time you where testing i suggested to upload the old system.
Anyway, i'm going to try this in the next days, while preparing a blender-unity image.

**Comment by MrFastwind** [comment]
steam-deploy@dcc23056f7adcaec16270b9f9715f6588c9a4c44
Is still using CyberAndrii/setup-steamcmd@v1.1.1; so it doesn't work for non root runners, are you sure is the right commit?

**Comment by MrFastwind** [comment]
should i take timewarpinc/steam-deploy@dcc23056f7adcaec16270b9f9715f6588c9a4c44 instead?

**Comment by MrFastwind** [comment]
only from steam-deploy@9226c2d6d34eb249ac56c30893fc1bd253a28e5a it started using docker...
I suppose you mean to use it from this commit.

**Comment by davidmfinol** [comment]
> only from steam-deploy@9226c2d6d34eb249ac56c30893fc1bd253a28e5a it started using docker... I suppose you mean to use it from this commit.

Yes, you are right, I meant `9226c2d6d34eb249ac56c30893fc1bd253a28e5a`. Does it work for you?

**Comment by MrFastwind** [comment]
it gives, Logging in user '***' to Steam Public...FAILED (Invalid Login Auth Code)
but in the steam_deploy.sh script is present
```
$STEAM_CMD +set_steam_guard_code "INVALID" +login "$steam_username" "$steam_password"  +quit;
```
wouldn't this make it impossible to login without steam guard code?
also is "INVALID" a defined constant? because steam cmd wiki shows nothing about it.
by the way i'm using ssfn files to login

**Comment by davidmfinol** [comment]
Fixed by https://github.com/game-ci/steam-deploy/pull/49
