### ISSUE TITLE
Running multiple times fails

### ISSUE THREAD

**Issue by vaartis** [game-ci/steam-deploy#53]
**Bug description**

When running the action multiple times (with different app ids) it fails.

```
Downloading ...
Destination file path D:\a\_temp\steamcmd.zip already exists
Waiting 10 seconds before trying again
Destination file path D:\a\_temp\steamcmd.zip already exists
Waiting 18 seconds before trying again
Error: Error: Destination file path D:\a\_temp\steamcmd.zip already exists
```

If `rm D:\a\_temp\steamcmd.zip` is run after the first time, everything works.

**How to reproduce**

Run the action more than once.

**Expected behavior**

It doesn't try to re-download steamcmd and re-initialize everything.

**Additional details**

It fails because steamcmd.zip already exists.

**Comment by davidmfinol** [comment]
We just released `game-ci/steam-deploy@v2`, which uses a Docker image instead of downloading steamcmd, so this issue should be fixed now.
Can you confirm that it works with  `game-ci/steam-deploy@v2`?

**Comment by vaartis** [comment]
Unfortunately it doesn't work for me: `Error: Container action is only supported on Linux` (I am building on windows).

**Comment by davidmfinol** [comment]
I'd recommend using the [upload-artifact](https://github.com/actions/upload-artifact) and [download-artifact](https://github.com/actions/download-artifact) actions to run the steam-deploy action on a linux runner. 
For example: https://game.ci/docs/github/deployment/steam

If you really need to do it all in the same runner (maybe for performance reasons), you could try forking both this action and https://github.com/CyberAndrii/setup-steamcmd and fix for yourself.

**Comment by vaartis** [comment]
I see. Very well, perhaps I'll do that sometime.
