### ISSUE TITLE
Enhance readme for macOS users

### ISSUE THREAD

**Issue by EdgarMagalhaes** [game-ci/steam-deploy#68]
Nice project, really helpful. 🙌

Just a suggestion regarding macOS users.
The `config.vdf` file is located at `~/Library/Application Support/Steam/config/config.vdf`.

**Comment by apotema** [comment]
Thanks for the help @EdgarMagalhaes 
Another thing worth mentioning is that you can't open Steam when generating the key.
I had Steam open for my account and was generating a key for another account, which generated a failed config.vdf file.
